### ISSUE TITLE
bootstrap mobile: remove background header graphic

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemyorg/sqlalchemyorg#13]
the header graphic on mobile gets in the way of the logo, easiest thing is to just have the header graphic not show up so there'd be just a white background.

![f3071e88-88a3-409a-b019-94a8dcc3b53c](https://user-images.githubusercontent.com/128223/152825046-a401a7bf-e7dd-4acc-8334-a510022d443c.png)

**Comment by CaselIT** [comment]
this is no longer relevant
