### ISSUE TITLE
"develop" page needs to refer developers to gitter channel, note weekly meetings

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemyorg/sqlalchemyorg#3]
for the weekly meetings, we should mention that they are a thing, but for the actual information, we refer people to the gitter channel, where the subject line has a link to the google doc, and the google doc has the schedule in it.

this way we aren't linking a google doc straight from the SQLAlchemy website which I'd rather not do and also we aren't hardcoding the meeting schedule on the website itself.

**Comment by zzzeek** [comment]
ping..... @jvanasco   ? :)

**Comment by jvanasco** [comment]
@zzzeek assign this to me and i'll take care of it.

**Comment by zzzeek** [comment]
fixed in #3
